
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Examination_App
{

using System;
    using System.Collections.Generic;
    
public partial class Department
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Department()
    {

        this.Ins_Dept_Cr = new HashSet<Ins_Dept_Cr>();

        this.Students = new HashSet<Student>();

    }


    public int Dept_Id { get; set; }

    public string Dept_Name { get; set; }

    public Nullable<int> Manager_Id { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Ins_Dept_Cr> Ins_Dept_Cr { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Student> Students { get; set; }

    public virtual Instructor Instructor { get; set; }

}

}
