
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Examination_App
{

using System;
    using System.Collections.Generic;
    
public partial class Ins_Dept_Cr
{

    public int Ins_Id { get; set; }

    public int Dept_id { get; set; }

    public int Cr_Id { get; set; }



    public virtual Course Course { get; set; }

    public virtual Department Department { get; set; }

    public virtual Instructor Instructor { get; set; }

}

}
