
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Examination_App
{

using System;
    using System.Collections.Generic;
    
public partial class Question
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Question()
    {

        this.Choices = new HashSet<Choice>();

        this.Exams = new HashSet<Exam>();

    }


    public int Q_Id { get; set; }

    public string Q_Content { get; set; }

    public string type { get; set; }

    public string Topic_Name { get; set; }

    public Nullable<int> Cr_Id { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Choice> Choices { get; set; }

    public virtual Topic Topic { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Exam> Exams { get; set; }

}

}
